export const ADD_BUG = 'ADD_BUG';
export const DELETE_BUG = 'DELETE_BUG';
export const GET_BUGS = 'GET_BUGS';
export const UPDATE_BUG = 'UPDATE_BUG';
export const RESET_BUGS = 'RESET_BUGS';
export const SET_LOADING_BUG = 'SET_LOADING_BUG';

export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const SET_LOADING = 'SET_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const UPDATE_USER_PROJECT = 'UPDATE_USER_PROJECT';

export const GET_CURRENT_PROJECT = 'GET_CURRENT_PROJECT';
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const GET_INVITED_PROJECT = 'GET_INVITED_PROJECT';
export const REQUESTED_USER = 'REQUESTED_USER';
